version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: login
      POSTGRES_USER: login
      POSTGRES_DB: login
    ports:
      - 5432:5432
